services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      default:
        aliases:
          - mongo  # ADD THIS - makes it reachable as 'mongo' too

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: password
    depends_on:
      - mongodb